### ISSUE TITLE
Is there a way to trigger onLeave when begin to leave

### ISSUE THREAD

**Issue by MickeyBadBad** [wellyshen/react-cool-inview#191]
I notice that OnEnter will trigger when the element starts to enter the viewport, but OnLeave triggers when the element fully leaves the viewport.
I think after the element leaves the viewport, trigger some function just not helping too much.
Is there any way to trigger onLeave when the beginning? maybe a prop or something will do.

Great Library, Thank you for your work.

**Comment by wellyshen** [comment]
@MickeyBadBad Maybe the `onChange` event can help you ([API](https://github.com/wellyshen/react-cool-inview#parameter)):

```js
const { ref, inView } = useInView({
  onChange: ({ inView }) => {
    if (!inView) {
      // Do something...
    }
  },
});
```

**Comment by MickeyBadBad** [comment]
@wellyshen I tried, but I notice that onChange is trigger when the page load and after onEnter or onLeave, and inView only return true when the element fully leaves the view point, i don't want that.

I want to do something when the element starts to leave, at the beginning of the scroll to leave action.

is there any way to do that?

**Comment by wellyshen** [comment]
@MickeyBadBad You can custom the trigger point of the **enter** and **leave** via the `onChange` event as below. Here's the live [example](https://codesandbox.io/s/playground-oyz6h?file=/src/App.tsx:0-745).

```js
import * as React from "react";
import useInView from "react-cool-inview";

const threshold = [0.2, 0.5];
let alreadyInView = false;

export default function App() {
  const { ref } = useInView({
    threshold,
    onChange: ({ entry }) => {
      const { intersectionRatio } = entry;

      if (intersectionRatio >= Math.min(...threshold) && !alreadyInView) {
        console.log("LOG ===> onEnter");
        alreadyInView = true;
      } else if (intersectionRatio <= Math.max(...threshold) && alreadyInView) {
        console.log("LOG ===> onLeave");
        alreadyInView = false;
      }
    }
  });

  return (
    <div className="App">
      <div className="target" ref={ref} />
    </div>
  );
}
```

**Comment by MickeyBadBad** [comment]
@wellyshen thankyou so much, I find threshold = [0.2,0.8] working like charm. (bigger than 0.8 , smaller than 0.2 will have some problem like OnEnter and Onleave with same enter viewpoint when actions is slow.)

great job, thanks.

**Comment by wellyshen** [comment]
@MickeyBadBad Congrats! If we want to custom your own trigger points, we need to fine-tune the threshold to avoid the conflict between enter and leave. But current leave/enter events are implemented based on the [IntersectionObserverEntry.isIntersecting](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/isIntersecting) mechanism, which handled by the API itself so we don't have to worry about it.
