### ISSUE TITLE
scrollDirection reports wrong direction

### ISSUE THREAD

**Issue by intelligence** [wellyshen/react-cool-inview#350]
Great hook you've put together, been using it for a while and it works like a treat!

I've discovered what I think is a bug. On the project I'm working on right now I have a navigation that jumps to different sections on the homepage. I've noticed that if I jump to a section (via `scrollTop`) and then scroll upwards, when `onEnter` triggers `scrollDirection.vertical` is `up`, when it should be `down`.

If I test with `onChange` I see `up` on the first threshold and the following ones will be `down` as expected.

I'm just getting ready to launch this project so I'll revisit this thread with a test case as soon as I have the time if you can't reproduce on your own.

Thanks again!

**Comment by wellyshen** [comment]
@intelligence Sorry for the late. It's a good case that I didn't expect before. I'll reproduce and handle this issue soon.

**Comment by wellyshen** [comment]
@intelligence You can correct the behavior via the new `updatePosition` API in the [latest version](https://github.com/wellyshen/react-cool-inview/releases/tag/v1.2.0).
