### ISSUE TITLE
README should include TypeScript examples

### ISSUE THREAD

**Issue by bradydowling** [wellyshen/react-cool-inview#455]
# Bug Report

## Describe the Bug

There are good examples in the README but it's tough to tell how to get this working in TypeScript. There is [an example](https://github.com/wellyshen/react-cool-inview/blob/d4201eb4eac68ff8687524d92e3b4965c4674506/demo/Card/index.tsx#L10) in the demo folder but this doesn't run immediately in CodeSandbox so it's a little challenging to find it from there.

Since most `ref`s from the hook will be used on `div`s, it would be helpful to have documentation in the README about the generic you can pass to make this work. Otherwise, you'll end up getting:

```
Type 'RefObject<HTMLElement>' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
  Type 'RefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLDivElement>'.
    Property 'align' is missing in type 'HTMLElement' but required in type 'HTMLDivElement'.  TS2322
```

## How to Reproduce

Use `useInView` in TypeScript without providing a generic.

**Comment by wellyshen** [comment]
@bradydowling Thank you, I will add it soon.

**Comment by wellyshen** [comment]
@bradydowling I have added the [related example](https://github.com/wellyshen/react-cool-inview#working-in-typescript), thank you :)
