### ISSUE TITLE
rootMargin must have pixel or percentage unit, but the “Trigger Animations” example uses a rootMargin of "-100px 0" which throws an error.

### ISSUE THREAD

**Issue by brandondurham** [wellyshen/react-cool-inview#486]
# Bug Report

## Describe the Bug

In the README file the [Trigger Animations](https://github.com/wellyshen/react-cool-inview#trigger-animations) example uses a value of `"-100px 0"` for `rootMargin`, but `rootMargin` requires absolute pixel or percent units, otherwise it throws the following error:

```
Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.
```

## How to Reproduce

Just follow the example set in the [Trigger Animations](https://github.com/wellyshen/react-cool-inview#trigger-animations) section of the README.

## CodeSandbox Link

https://codesandbox.io/s/react-cool-inview-example-forked-bcf57

## Expected Behavior

`0` shouldn’t require a unit.

## Screenshots

Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/250210/112694771-ee365c80-8e50-11eb-8421-99fb420006f6.png)

## Your Environment

- Device: MacBook
- OS: macOS BigSur 11.1
- Browser: Chrome
- Version: 89.0.4389.90 (Official Build) (x86_64)

**Comment by brandondurham** [comment]
Referenced here: https://github.com/w3c/IntersectionObserver/pull/453

**Comment by wellyshen** [comment]
@brandondurham Sorry for the late reply, I have updated the READ.md.

**Comment by brandondurham** [comment]
Thank you!
