### ISSUE TITLE
Custom Ref not checked before calling (un)observe

### ISSUE THREAD

**Issue by stramel** [wellyshen/react-cool-inview#494]
# Bug Report

## Describe the Bug

If passing a custom `ref` to the hook, the `observe` and `unobserve` functions aren't checking that it isn't `null` before treating it as an `Element`.

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Conditionally apply the ref
2. Change condition to false
3. Scroll
4. Observe error `Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.`

## CodeSandbox Link

https://codesandbox.io/s/xenodochial-black-cd5lo?file=/src/App.js

## Expected Behavior

I would expect no error

## Screenshots

![image](https://user-images.githubusercontent.com/855184/113339738-8ec4ca80-92f0-11eb-8d56-921660f17b74.png)

## Your Environment

- Device: MacBook Pro
- OS: macOS X
- Browser: Chrome
- Version: v1.2.2

## Additional Information

It looks like there is a missing safety check that the `ref.current` isn't `null`.

**Comment by wellyshen** [comment]
@stramel The `ref` option should be used as follows, so it receives a `ref` object only.

```js
export default function App() {
  const [items, setItems] = useState([]);
  const ref = useRef();
  useInView({
    ref,
    rootMargin: "50px 0px",
    async onEnter({ observe, unobserve }) {
      unobserve();

      await new Promise((res) => {
        // Simulating data coming in from API
        setTimeout(() => {
          setItems([]);
          res();
        }, 200);
      });
      observe();
    }
  });

  useEffect(() => {
    // Simulating data coming in from API
    setTimeout(() => {
      setItems(createItems());
    }, 200);
  }, []);

  return (
    <div className="App">
      {items.map((item, i) => {
        return i === items.length - 1 ? (
          <pre ref={ref} key={item.id}>
            {JSON.stringify(item, undefined, 2)}
          </pre>
        ) : (
          <pre key={item.id}>{JSON.stringify(item, undefined, 2)}</pre>
        );
      })}
    </div>
  );
}
```

**Comment by stramel** [comment]
@wellyshen The `ref` setup that I used above was to work around #493. With v1.3.0, it seems to address the missed check. I'm wiling to close this now, Thank you!
