### ISSUE TITLE
rootMargin not working until after the first time intersecting

### ISSUE THREAD

**Issue by stramel** [wellyshen/react-cool-inview#495]
# Bug Report

## Describe the Bug

The `rootMargin` is being ignore until after the first time the `IntersectionObserver` fires `isIntersecting`. 

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Provide custom `rootMargin` and custom `ref`
2. Scroll down
3. Observe the `isIntersecting` is `false` until the element is visible.
4. Scroll down again
5. Observe the `isIntersecting` is `true` at the expected `rootMargin`

## CodeSandbox Link

https://codesandbox.io/s/react-cool-inviewissues495-0g4yk

## Expected Behavior

Should respect the `rootMargin` on the initial scroll

## Screenshots

![image](https://user-images.githubusercontent.com/855184/113344333-8a9bab80-92f6-11eb-8601-e6c2388a958f.png)

## Your Environment

- Device: MacBook Pro
- OS: macOS X
- Browser: Chrome
- Version: v1.2.2

**Comment by wellyshen** [comment]
@stramel Thank you for reporting this issue, I know the root cause, will fix it soon!

**Comment by stramel** [comment]
> Thank you for reporting this issue, I know the root cause, will fix it soon!

Thanks! Just wanted to confirm that it is still an issue with v1.3.0 https://codesandbox.io/s/react-cool-inviewissues495-with-v130-zosed

**Comment by wellyshen** [comment]
@stramel Thank you for your support, I think this issue should be fixed in [v1.3.1](https://github.com/wellyshen/react-cool-inview/releases/tag/v1.3.1).

**Comment by stramel** [comment]
@wellyshen It does appear that it works properly in a CRA environment. So this probably isn't a bug with the library but maybe one with the browser's Intersection Observer implementation.

I did notice, that it looks like the state isn't reset properly?

![image](https://user-images.githubusercontent.com/855184/113496739-31807300-94c2-11eb-8fd6-c9190c8277b2.png)


The `inView` says `true` after the `observe` is called and the new `ref` has been set. As well as, the `scrollDirection` is resetting to `'up'` even though I never scrolled up. 

https://github.com/stramel/react-cool-inview-issue-495

**Comment by wellyshen** [comment]
@stramel That make sense, I will fix the scrollDirection part soon.

**Comment by wellyshen** [comment]
@stramel The `scrollDirection` should be reset correctly in [v2.0.1](https://github.com/wellyshen/react-cool-inview/releases/tag/v2.0.1).

**Comment by stramel** [comment]
Going to close this issue in favor of a new one to show the other issues that I have found with `scrollDirection` and `inView`.

**Comment by wellyshen** [comment]
@stramel Thank you bro, your issues are really helpful.

**Comment by stramel** [comment]
Thanks for the cool 😎 library! 👍🏼
