### ISSUE TITLE
ScrollDirection isn't displaying the proper direction

### ISSUE THREAD

**Issue by stramel** [wellyshen/react-cool-inview#499]
# Bug Report

## Describe the Bug

While scrolling down, the `scrollDirection` doesn't update to say `'down'`. When the new page of items loads, it causes the scroll bar to jump and reports the `scrollDirection` of `'up'` of which, I (the user) never scrolled up and can be misleading.

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup infinite scroll
2. Scroll down
3. Observe no `scrollDirection` while scrolling down
4. Observe `scrollDirection` of `'up'` when the screen repaints with new items

## CodeSandbox Link

https://codesandbox.io/s/react-cool-inviewissues499-kl2xg

## Expected Behavior

I would expect while scrolling to show the direction I'm scrolling.
I would expect after a period of time not scrolling, to remove the scrollDirection.
I would expect when new items load/render, the `scrollDirection` won't report the jump up.

## Screenshots
![image](https://user-images.githubusercontent.com/855184/113514971-43e8c400-9537-11eb-8456-b765f3725fb5.png)

Then scrolling after new load: 
![image](https://user-images.githubusercontent.com/855184/113514981-5662fd80-9537-11eb-8b32-ec8fad79665c.png)

## Your Environment

- Device: MacBook Pro
- OS: macOS X
- Browser: Chrome
- Version: v2.0.1

**Comment by wellyshen** [comment]
@stramel Thank you. I Will fix the direction tomorrow, it pretty late in Taiwan.

**Comment by wellyshen** [comment]
@stramel This issue should be fixed in [v2.0.2](https://github.com/wellyshen/react-cool-inview/releases/tag/v2.0.2)

**Comment by stramel** [comment]
@wellyshen I think there has been some miscommunication around this issue. This PR #501 inverted the `scrollDirection` and probably needs reverted.

There were a couple things I noticed, each I believe should be addressed:

1. While scrolling down, the scrollDirection is reporting `undefined`. I would expect it to report `'down'`.
2. After, scrolling down and new items are added via the infinite scroll the `scrollDirection` reports `up` when the new items render causing the scroll bar to jump
3. While not scrolling, the previously reported `scrollDirection` stays

I believe that the issue is that maybe the `scrollDirection` isn't properly triggering an update.

What I would expect for each situation:

> 1. While scrolling down, the scrollDirection is reporting `undefined`. I would expect it to report `'down'`.

`scrollDirection` should update from `undefined` to `'down'` when I start scrolling down. (Currently, doesn't report anything)
![image](https://user-images.githubusercontent.com/855184/113588916-55dd6c00-95f6-11eb-8aac-a890e6d948c2.png)

> 2. After, scrolling down and new items are added via the infinite scroll the `scrollDirection` reports `up` when the new items render causing the scroll bar to jump

`scrollDirection` should not report `up` when the new items render. After calling `unobserve` I would expect no update on the `scrollDirection`.

![image](https://user-images.githubusercontent.com/855184/113589086-9341f980-95f6-11eb-9548-6a07a53bfac5.png)

> 3. While not scrolling, the previously reported `scrollDirection` stays

I would expect `scrollDirection` to clear after a period of time of not scrolling.

**Comment by stramel** [comment]
I believe the issue is that I misunderstood how the `scrollDirection` reports. It does report as it is documented in the lib. However, #501 should be reverted. Sorry for the inconvenience!

**Comment by wellyshen** [comment]
@stramel I think I should do more advanced research about the definition of scrolling up/down before reverting it, let me keep this issue open.

**Comment by stramel** [comment]
@wellyshen I just wanted to point out that scrolling down shows `scrollDirection.vertical` as `'up'` with #501 https://codesandbox.io/s/react-cool-inview-issue-499-inverted-scrolling-v202-7kw28

**Comment by wellyshen** [comment]
@stramel I think this issue should be fixed in [v2.0.3](https://github.com/wellyshen/react-cool-inview/releases/tag/v2.0.3)

**Comment by stramel** [comment]
Thank you!
