### ISSUE TITLE
inView is reporting incorrect value after loading more items until scroll.

### ISSUE THREAD

**Issue by stramel** [wellyshen/react-cool-inview#500]
# Bug Report

## Describe the Bug

The `inView` is still tracking the status of the initial last item after loading additional items.

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup infinite scrolling example
2. Scroll down
3. Observe `inView` remains `true` even after loading new items and settings new item with `observe`
4. Observe the `inView` variable switches to `false` once the previously tracked item is fully off screen

## CodeSandbox Link

https://codesandbox.io/s/react-cool-inviewissues500-qsn5q

## Expected Behavior

I would expect after loading new items, and a new `ref`/`observe` being applied, that the previously tracked item, is no longer tracked and `inView` to report `false`.

## Screenshots

![image](https://user-images.githubusercontent.com/855184/113515074-e30dbb80-9537-11eb-8f35-7f78eef19bb8.png)

Turns `false` after the initial last item (20 in the example) is off screen:
![image](https://user-images.githubusercontent.com/855184/113515113-21a37600-9538-11eb-970d-03f879e257a2.png)

## Your Environment

- Device: MacBook Pro
- OS: macOS X
- Browser: Chrome
- Version: v2.0.1

## Additional Information

On an infinite scroll style example, I don't believe the `observe` is necessary within `onEnter` since the `ref` is calling the `observe`

**Comment by wellyshen** [comment]
@stramel Thank you, will investigate it tomorrow 👍🏻

**Comment by wellyshen** [comment]
@stramel This issue should be fixed in [v2.0.2](https://github.com/wellyshen/react-cool-inview/releases/tag/v2.0.2)

**Comment by stramel** [comment]
Thank you for the quick fix @wellyshen!

Confirmed this issue has been resolved with v2.0.2. 
fixed: https://codesandbox.io/s/react-cool-inviewissues500-fixed-ebpqw
