### ISSUE TITLE
Typescript typing wrong for observe

### ISSUE THREAD

**Issue by cameronbraid** [wellyshen/react-cool-inview#504]
You need to change `observe` to accept an optional element

I get an error when using useInView and useDimensions when trying to compose the observe callback :

```
  const { observe:observeInView, inView } = useInView({...})

  const { observe:observeDimension, currentBreakpoint } = useDimensions({...})

  let combinedObserve = useCallback(el=>{
    observeInView(el);
    observeDimension(el);
  }, [observeInView, observeDimension])

```

ts error is `Expected 0 arguments, but got 1.ts(2554)`

This is because observe is defined as :

```
    observe: () => void;
```

it needs to look something like

```
    observe: (element?: HTMLElement) => void
```

**Comment by wellyshen** [comment]
@cameronbraid The type should be `observer: (element?: T) => void` (https://github.com/wellyshen/react-cool-inview/blob/master/src/react-cool-inview.d.ts#L14) already. Which version that you're using?

**Comment by cameronbraid** [comment]
I am on `2.0.2` For some reason my npm wont upgrade to `2.0.3` but that's my problem not yours :)

Thanks mate.
