### ISSUE TITLE
Request support for multiple refs

### ISSUE THREAD

**Issue by mnpappo** [wellyshen/react-cool-inview#638]
## Description

It's very normal to observe more than one element. Tracking visibility or lazy loading doesn't stop at only one component. I think it would be great if the library supports multiple refs. 

## Possible solution

`react-intersection-observer` use [useCallback](https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component) method inside a component  to set the current node ref using `useRef` from react.  I am sure you already looked into it but if you make a workaround or a stable solution out of it that would be very helpful.

**Comment by wellyshen** [comment]
@mnpappo You can achieve that via this [example](https://github.com/wellyshen/react-cool-inview#how-to-share-a-ref). It works the same with `react-intersection-observer`.

**Comment by mnpappo** [comment]
Cool, thank you @wellyshen
