### ISSUE TITLE
SEO Question

### ISSUE THREAD

**Issue by vahidtakro** [wellyshen/react-cool-inview#640]
Hello, as a new React Next.js learner, I have a question.
Today I got this amazing package for my react app, and put my <Image> comp between `inView` so it only shows posts images on scroll, which makes the posts so fast and cool.
My question is,
Are photos still indexable by Google? Google will find the pictures and posts? How it will effect the SEO generally?

Thanks

**Comment by wellyshen** [comment]
@vahidtakro Thank you for giving this package a try. For lazy image SEO, you can check this [doc](https://developers.google.com/search/docs/advanced/javascript/lazy-loading) and [test](https://developers.google.com/search/docs/advanced/javascript/lazy-loading#test) the result of your implemenation.
