### ISSUE TITLE
Using cool inview only for src in a component

### ISSUE THREAD

**Issue by vahidtakro** [wellyshen/react-cool-inview#641]
Hello, how can I use `{inView && ... }` inside a component? for example I want my Image just to be loaded in view, but it loads `blurDataURL` even before scrolling.
```
export default function Image({ src, ...rest }) {
  const { observe, inView } = useInView({
    onEnter: ({ unobserve }) => unobserve(), // only run once
  })
  return (
    <div ref={observe} className="max-w-screen-sm mx-auto text-center">
      <NextImage
        placeholder="blur"
        blurDataURL={`/_next/image?url=${src}&w=16&q=1`}
        src={`/_next/image?url=${src}&w=640&q=75`}
        {...rest}
      />
    </div>
  )
}
```

I was actually using inview for the whole component like this:
```
{inView &&   
<NextImage
    placeholder="blur"
    blurDataURL={`/_next/image?url=${src}&w=16&q=1`}
    src={`/_next/image?url=${src}&w=640&q=75`}
    {...rest}
/>}
```

but then I found that my Table of Content will be useless, because once the user clicks on them, it takes them to the wrong text, because images are not still all loaded. so then I decided to only use inView (which I don't know how to) for src only.
what do you think?

Thanks

**Comment by wellyshen** [comment]
@vahidtakro Next image already supports [lazy image loading](https://nextjs.org/docs/api-reference/next/image#loading) I think you can use it directly without this package.
