### ISSUE TITLE
Infinite re-renders

### ISSUE THREAD

**Issue by dungle-scrubs** [wellyshen/react-cool-inview#850]
# Bug Report

## Describe the Bug

When I use this hook in any component, it causes infinite re-renders. Am I doing something wrong?

## CodeSandbox Link

You can see it here: [CodeSandbox](https://codesandbox.io/s/react-cool-inview-7vqstj?file=/src/Component.js).

Thanks

**Comment by wellyshen** [comment]
The re-render was caused by repeatedly `observe()` and `unobserve()`, i.e. the line 11 and 12.
